# サンプルAPI
@baseUrl = http://localhost:2000/api/v1/

###
# サンプル（取得）
# @name getSetting
GET {{baseUrl}}setting/ HTTP/1.1
Content-Type: application/json

###
# サンプル（登録）
# @name postSetting
POST {{baseUrl}}setting/submit HTTP/1.1
Content-Type: application/json

{
    "invoiceDetail": [
        {
            "mstPpolItemId": 1,
            "name": "請求書番号",
            "isDisplay": 1,
            "sortOrder": 2
        },
        {
            "mstPpolItemId": 2,
            "name": "請求書の発行日",
            "isDisplay": 1,
            "sortOrder": 1
        },
        {
            "mstPpolItemId": 3,
            "name": "請求書の発行時間",
            "isDisplay": 0,
            "sortOrder": 3
        },
        {
            "mstPpolItemId": 4,
            "name": "請求書の通貨コード",
            "isDisplay": 1,
            "sortOrder": 4
        },
        {
            "mstPpolItemId": 5,
            "name": "支払期限",
            "isDisplay": 1,
            "sortOrder": 5
        },
        {
            "mstPpolItemId": 6,
            "name": "請求書タイプコード",
            "isDisplay": 1,
            "sortOrder": 6
        }
    ],
    "particulars": [
        {
            "mstPpolItemId": 7,
            "name": "請求書品目識別子",
            "isDisplay": 0,
            "sortOrder": 7
        },
        {
            "mstPpolItemId": 8,
            "name": "請求書明細メモ",
            "isDisplay": 1,
            "sortOrder": 8
        }
    ]
}
