# @format

version: "3"

services:
  ####################
  # nginx
  ####################
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: ./docker-local/nginx/
    ports:
      - "2000:80"
    volumes:
      - ./src/:/usr/share/nginx/html
      - ./docker-local/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - python
      - vue
    networks:
      - common
  ####################
  # vue
  ####################
  vue:
    container_name: ${COMPOSE_PROJECT_NAME}-vue
    build:
      context: ./docker-local/vue
    ports:
      - "1000:80"
    environment:
      APP_ENV: ${APP_ENV}
    volumes:
      - ./frontend:/app
    tty: true
    command: npm run dev
    networks:
      - common

  ####################
  # python
  ####################
  python:
    # env_file:
    container_name: ${COMPOSE_PROJECT_NAME}-python
    build:
      context: .
      dockerfile: ./docker-local/python/Dockerfile
    privileged: true
    platform: linux/amd64
    ports:
      - "8000:8000"
      - "5001:5678"
    environment:
      APP_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      PYTHONPATH: ${PYTHONPATH}
      TZ: "Asia/Tokyo"
      # PYTHONUSERBASE: /app/packages
      # PATH: $PATH:/vendor/bin
    volumes:
      - ./backend/src:/app
      - ./pyproject.toml:/app/pyproject.toml
    tty: true
    networks:
      - common

####################
# common
####################
networks:
  common:
    driver: bridge
