"""tests/api/test_PP007_params.py"""

import datetime
import logging
from typing import Any

import api.v1.schemas.invoice as invoice_schema
from api.v1.schemas.base_schema import Header
from api.v1.schemas.error_schema import ErrorModel
from api.v1.schemas.invoices.downloads.previews import BaseItem
from core.constant import const
from core.message import messages
from enums import (
    DataType,
    InputTaxType,
    PaymentMethod,
    ReducedTaxFlg,
    SumExemptFlg,
    TaxCalcType,
    TaxType,
)
from exceptions.peppol_http_exception import PeppolHttpException
from fastapi import status
from models import CompanyInfo, Invoice


def test_PP007() -> list[tuple[int, CompanyInfo, list[int], BaseItem, dict[str, Any]]]:
    """PP007APIテストパラメータ"""
    mock_invoice = Invoice(
        data_type=DataType.STANDARD,
        IBT005="unittestIBT005",
        customer=invoice_schema.CustomerItem(
            peppol_scheme_id="unittestPeppolSchemeId",
            peppol_id="unittestPeppolId",
            tax_corp_id="unittestTaxCorpId",
            private_cust_cd="unittestPrivateCustCd",
            corp_genuine_id=1,
            company_name_org="unittestCompanyNameOrg",
            zip="unittestZip",
            country_subentity="unittestCountrySubentity",
            city_name="unittestCityName",
            street_name="unittestStreetName",
            user_email="unittestUserEmail",
            phone="unittestPhone",
        ),
        publisher=invoice_schema.PublisherItem(
            publisher_peppol_scheme_id="unittestPublisherPeppolSchemeId",
            publisher_peppol_id="unittestPublisherPeppolId",
            publisher_corp_genuine_id=1,
            publisher_tax_corp_id="unittestPublisherTaxCorpId",
            publisher_mail="unittestPublisherMail",
            publisher_company_name_org="unittestPublisherCompanyNameOrg",
            publisher_mng_num="unittestPublisherMngNum",
            publisher_company_name="unittestPublisherCompanyName",
            publisher_section="unittestPublisherSection",
            publisher_zip="unittestPublisherZip",
            publisher_country_subentity="unittestPublisherCountrySubentity",
            publisher_city_name="unittestPublisherCityName",
            publisher_street_name="unittestPublisherStreetName",
            publisher_phone="unittestPublisherPhone",
            biz_type="unittestBizType",
            biz_regist_no="unittestBizRegistNo",
            nta_biz_regist_no_result="unittestNtaBizRegistNoResult",
            nta_registered_date="unittestNtaRegisteredDate",
            nta_process="unittestNtaProcess",
            nta_company_name="unittestNtaCompanyName",
            nta_area="unittestNtaArea",
            nta_address="unittestNtaAddress",
            nta_update_date="unittestNtaUpdateDate",
            nta_trade_name="unittestNtaTradeName",
            nta_common_name="unittestNtaCommonName",
            nta_cancel_date="unittestNtaCancelData",
            nta_lapse_date="unittestNtaLapseDate",
        ),
        contact="鈴木 春香",
        list_info=invoice_schema.ListInfoItem(
            product_sec="unittestProductSec",
            private_user_name="unittestPrivateUserName",
            approver_name="unittestApproverName",
            billing_name="unittestBillingName",
            issue_user_name="unittestIssueUserName",
            phone="unittestPhone",
            send_date="unittestSendDate",
            remind_date="unittestRemindDate",
            seal_flg=False,
            fax_send_flg=False,
            qa_history=False,
            seal_date="unittestSealDate",
            destination_code="unittestDestinationCode",
            destination_name="unittestDestinationName",
        ),
        inv_no="1",
        close_date=datetime.datetime(year=2024, month=5, day=28),
        pay_due_date=datetime.datetime(year=2024, month=5, day=27),
        inv_amount=100000,
        inv_name="unittestInvName",
        prev_inv_amount=10,
        payment=10000,
        adjustment=1000,
        carryover_new=10000,
        inv_without_tax=1000,
        inv_tax=1000,
        inv_show_amount=1000,
        inv_without_tax_tr10=1000,
        inv_without_tax_tr8=1000,
        inv_without_tax_tr8_reduced=1000,
        inv_without_tax_tr5=1000,
        inv_without_tax_tr0=1000,
        inv_without_tax_free=1000,
        inv_without_tax_non=1000,
        inv_without_tax_exemption=1000,
        inv_tax_tr10=1000,
        inv_tax_tr8=1000,
        inv_tax_tr8_reduced=1000,
        inv_tax_tr5=1000,
        inv_tax_tr0=1000,
        inv_tax_free=1000,
        inv_tax_non=1000,
        inv_tax_exemption=1000,
        inv_amount_tr10=1000,
        inv_amount_tr8=1000,
        inv_amount_tr8_reduced=1000,
        inv_amount_tr5=1000,
        inv_amount_tr0=1000,
        inv_amount_free=1000,
        inv_amount_non=1000,
        inv_amount_exemption=1000,
        payment_method=PaymentMethod.BANK_TRANSFER,
        banks=[
            invoice_schema.BanksItem(
                transfer_code="unittestTransferCode",
                fncl_inst_code="unittestFnclInstCode",
                fncl_inst_name="unittestFnclInstName",
                fncl_inst_kana="unittestFnclInstKana",
                branch_code="unittestBranchCode",
                branch_name="unittestBranchName",
                branch_kana="unittestBranchKana",
                deposit_sec="unittestDepositSec",
                account_num="unittestAccountNum",
                depositor_name="unittestDepositorName",
                depositor_kana="unittestDepositorKana",
            )
        ],
        remarks="unittestRemarks",
        details=[
            invoice_schema.DetailsItem(
                item_slip_date="unittestItemSlipDate",
                item_slip_no="unittestItemSlipNo",
                item_prod_code="unittestItemProdCode",
                item_name="unittestItemName",
                item_qty=1,
                item_price=100,
                item_unit="unittestItemUnit",
                item_without_tax=10000,
                item_tax=1000,
                item_amount=11000,
                item_sec_code="unittestItemSecCode",
                item_sec_name="unittestItemSecName",
                detail_remarks="unittestDetailRemarks",
                item_free_txt1="unittestItemFreeTxt",
                item_free_txt2="unittestItemFreeTxt2",
                item_free_txt3="unittestItemFreeTxt3",
                item_free_txt4="unittestItemFreeTxt4",
                item_free_txt5="unittestItemFreeTxt5",
                item_free_txt6="unittestItemFreeTxt6",
                item_free_txt7="unittestItemFreeTxt7",
                item_free_txt8="unittestItemFreeTxt8",
                item_free_txt9="unittestItemFreeTxt9",
                item_free_txt10="unittestItemFreeTxt10",
                item_free_txt_l="unittestItemFreeTxtl",
                tax_type=TaxType.TAX,
                tax_rate_sec=10,
                reduced_tax_flg=ReducedTaxFlg.REDUCED,
                input_tax_type=InputTaxType.INPUT_TAX,
                tax_calc_type=TaxCalcType.WITH_OUT_TAX,
                sum_exempt_flg=SumExemptFlg.SUM_EXEMPT,
            )
        ],
    )

    return [
        # case 1 : invoice_id:1のプレビュー用データを取得
        (
            1,
            CompanyInfo(
                id=1, esCompanyId=1, name="unittestCompanyName1", parentEsCompanyId=1
            ),
            [1],
            BaseItem(
                data_type=mock_invoice.data_type,
                currencyCode=mock_invoice.IBT005,
                customer=mock_invoice.customer,
                publisher=mock_invoice.publisher,
                contact=mock_invoice.contact,
                list_info=mock_invoice.list_info,
                inv_no=mock_invoice.inv_no,
                close_date=(
                    mock_invoice.close_date.strftime(const.DATE_FORMAT)
                    if mock_invoice.close_date is not None
                    else None
                ),
                pay_due_date=(
                    mock_invoice.pay_due_date.strftime(const.DATE_FORMAT)
                    if mock_invoice.pay_due_date is not None
                    else None
                ),
                inv_amount=mock_invoice.inv_amount,
                inv_name=mock_invoice.inv_name,
                prev_inv_amount=mock_invoice.prev_inv_amount,
                payment=mock_invoice.payment,
                adjustment=mock_invoice.adjustment,
                carryover_new=mock_invoice.carryover_new,
                inv_without_tax=mock_invoice.inv_without_tax,
                inv_tax=mock_invoice.inv_tax,
                inv_show_amount=mock_invoice.inv_show_amount,
                inv_without_tax_tr10=mock_invoice.inv_without_tax_tr10,
                inv_without_tax_tr8=mock_invoice.inv_without_tax_tr8,
                inv_without_tax_tr8_reduced=mock_invoice.inv_without_tax_tr8_reduced,
                inv_without_tax_tr5=mock_invoice.inv_without_tax_tr5,
                inv_without_tax_tr0=mock_invoice.inv_without_tax_tr0,
                inv_without_tax_free=mock_invoice.inv_without_tax_free,
                inv_without_tax_non=mock_invoice.inv_without_tax_non,
                inv_without_tax_exemption=mock_invoice.inv_without_tax_exemption,
                inv_tax_tr10=mock_invoice.inv_tax_tr10,
                inv_tax_tr8=mock_invoice.inv_tax_tr8,
                inv_tax_tr8_reduced=mock_invoice.inv_tax_tr8_reduced,
                inv_tax_tr5=mock_invoice.inv_tax_tr5,
                inv_tax_tr0=mock_invoice.inv_tax_tr0,
                inv_tax_free=mock_invoice.inv_tax_free,
                inv_tax_non=mock_invoice.inv_tax_non,
                inv_tax_exemption=mock_invoice.inv_tax_exemption,
                inv_amount_tr10=mock_invoice.inv_amount_tr10,
                inv_amount_tr8=mock_invoice.inv_amount_tr8,
                inv_amount_tr8_reduced=mock_invoice.inv_amount_tr8_reduced,
                inv_amount_tr5=mock_invoice.inv_amount_tr5,
                inv_amount_tr0=mock_invoice.inv_amount_tr0,
                inv_amount_free=mock_invoice.inv_amount_free,
                inv_amount_non=mock_invoice.inv_amount_non,
                inv_amount_exemption=mock_invoice.inv_amount_exemption,
                payment_method=mock_invoice.payment_method,
                banks=mock_invoice.banks,
                remarks=mock_invoice.remarks,
                details=mock_invoice.details,
            ),
            {
                "header": {"code": "", "message": ""},
                "payload": {
                    "data_type": 1,
                    "currencyCode": "unittestIBT005",
                    "customer": {
                        "peppol_scheme_id": "unittestPeppolSchemeId",
                        "peppol_id": "unittestPeppolId",
                        "tax_corp_id": "unittestTaxCorpId",
                        "private_cust_cd": "unittestPrivateCustCd",
                        "corp_genuine_id": 1,
                        "company_name_org": "unittestCompanyNameOrg",
                        "zip": "unittestZip",
                        "country_subentity": "unittestCountrySubentity",
                        "city_name": "unittestCityName",
                        "street_name": "unittestStreetName",
                        "user_email": "unittestUserEmail",
                        "phone": "unittestPhone",
                    },
                    "publisher": {
                        "publisher_peppol_scheme_id": "unittestPublisherPeppolSchemeId",
                        "publisher_peppol_id": "unittestPublisherPeppolId",
                        "publisher_corp_genuine_id": 1,
                        "publisher_tax_corp_id": "unittestPublisherTaxCorpId",
                        "publisher_mail": "unittestPublisherMail",
                        "publisher_company_name_org": "unittestPublisherCompanyNameOrg",
                        "publisher_mng_num": "unittestPublisherMngNum",
                        "publisher_company_name": "unittestPublisherCompanyName",
                        "publisher_section": "unittestPublisherSection",
                        "publisher_zip": "unittestPublisherZip",
                        "publisher_country_subentity": "unittestPublisherCountrySubentity",
                        "publisher_city_name": "unittestPublisherCityName",
                        "publisher_street_name": "unittestPublisherStreetName",
                        "publisher_phone": "unittestPublisherPhone",
                        "biz_type": "unittestBizType",
                        "biz_regist_no": "unittestBizRegistNo",
                        "nta_biz_regist_no_result": "unittestNtaBizRegistNoResult",
                        "nta_registered_date": "unittestNtaRegisteredDate",
                        "nta_process": "unittestNtaProcess",
                        "nta_company_name": "unittestNtaCompanyName",
                        "nta_area": "unittestNtaArea",
                        "nta_address": "unittestNtaAddress",
                        "nta_update_date": "unittestNtaUpdateDate",
                        "nta_trade_name": "unittestNtaTradeName",
                        "nta_common_name": "unittestNtaCommonName",
                        "nta_cancel_date": "unittestNtaCancelData",
                        "nta_lapse_date": "unittestNtaLapseDate",
                    },
                    "contact": "鈴木 春香",
                    "list_info": {
                        "product_sec": "unittestProductSec",
                        "private_user_name": "unittestPrivateUserName",
                        "approver_name": "unittestApproverName",
                        "billing_name": "unittestBillingName",
                        "issue_user_name": "unittestIssueUserName",
                        "phone": "unittestPhone",
                        "send_date": "unittestSendDate",
                        "remind_date": "unittestRemindDate",
                        "seal_flg": False,
                        "fax_send_flg": False,
                        "qa_history": False,
                        "seal_date": "unittestSealDate",
                        "destination_code": "unittestDestinationCode",
                        "destination_name": "unittestDestinationName",
                    },
                    "inv_no": "1",
                    "close_date": "2024-05-28",
                    "pay_due_date": "2024-05-27",
                    "inv_amount": 100000,
                    "inv_name": "unittestInvName",
                    "prev_inv_amount": 10,
                    "payment": 10000,
                    "adjustment": 1000,
                    "carryover_new": 10000,
                    "inv_without_tax": 1000,
                    "inv_tax": 1000,
                    "inv_show_amount": 1000,
                    "inv_without_tax_tr10": 1000,
                    "inv_without_tax_tr8": 1000,
                    "inv_without_tax_tr8_reduced": 1000,
                    "inv_without_tax_tr5": 1000,
                    "inv_without_tax_tr0": 1000,
                    "inv_without_tax_free": 1000,
                    "inv_without_tax_non": 1000,
                    "inv_without_tax_exemption": 1000,
                    "inv_tax_tr10": 1000,
                    "inv_tax_tr8": 1000,
                    "inv_tax_tr8_reduced": 1000,
                    "inv_tax_tr5": 1000,
                    "inv_tax_tr0": 1000,
                    "inv_tax_free": 1000,
                    "inv_tax_non": 1000,
                    "inv_tax_exemption": 1000,
                    "inv_amount_tr10": 1000,
                    "inv_amount_tr8": 1000,
                    "inv_amount_tr8_reduced": 1000,
                    "inv_amount_tr5": 1000,
                    "inv_amount_tr0": 1000,
                    "inv_amount_free": 1000,
                    "inv_amount_non": 1000,
                    "inv_amount_exemption": 1000,
                    "payment_method": 0,
                    "banks": [
                        {
                            "transfer_code": "unittestTransferCode",
                            "fncl_inst_code": "unittestFnclInstCode",
                            "fncl_inst_name": "unittestFnclInstName",
                            "fncl_inst_kana": "unittestFnclInstKana",
                            "branch_code": "unittestBranchCode",
                            "branch_name": "unittestBranchName",
                            "branch_kana": "unittestBranchKana",
                            "deposit_sec": "unittestDepositSec",
                            "account_num": "unittestAccountNum",
                            "depositor_name": "unittestDepositorName",
                            "depositor_kana": "unittestDepositorKana",
                        }
                    ],
                    "remarks": "unittestRemarks",
                    "details": [
                        {
                            "item_slip_date": "unittestItemSlipDate",
                            "item_slip_no": "unittestItemSlipNo",
                            "item_prod_code": "unittestItemProdCode",
                            "item_name": "unittestItemName",
                            "item_qty": 1,
                            "item_price": 100,
                            "item_unit": "unittestItemUnit",
                            "item_without_tax": 10000,
                            "item_tax": 1000,
                            "item_amount": 11000,
                            "item_sec_code": "unittestItemSecCode",
                            "item_sec_name": "unittestItemSecName",
                            "detail_remarks": "unittestDetailRemarks",
                            "item_free_txt1": "unittestItemFreeTxt",
                            "item_free_txt2": "unittestItemFreeTxt2",
                            "item_free_txt3": "unittestItemFreeTxt3",
                            "item_free_txt4": "unittestItemFreeTxt4",
                            "item_free_txt5": "unittestItemFreeTxt5",
                            "item_free_txt6": "unittestItemFreeTxt6",
                            "item_free_txt7": "unittestItemFreeTxt7",
                            "item_free_txt8": "unittestItemFreeTxt8",
                            "item_free_txt9": "unittestItemFreeTxt9",
                            "item_free_txt10": "unittestItemFreeTxt10",
                            "item_free_txt_l": "unittestItemFreeTxtl",
                            "tax_type": "0",
                            "tax_rate_sec": 10,
                            "reduced_tax_flg": "1",
                            "input_tax_type": "2",
                            "tax_calc_type": "0",
                            "sum_exempt_flg": "1",
                        }
                    ],
                },
            },
        ),
    ]


test_PP007_exception = [
    (
        # case 1 : I0001: invoice_idパラメーターが数値ではない
        "a",
        None,
        None,
        None,
        ErrorModel(
            header=Header(
                code=messages.INVALID_PARAMETER.code,
                message="invoice_id is Input should be a valid integer, unable to parse string as an integer",
            ),
            payload=None,
        ).model_dump(mode="json"),
        status.HTTP_422_UNPROCESSABLE_ENTITY,
    ),
    (
        # case 2 : I0002: 該当請求書レコードが存在しない
        1,
        CompanyInfo(
            id=1, esCompanyId=1, name="unittestCompanyName1", parentEsCompanyId=1
        ),
        [1],
        PeppolHttpException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            log_level=logging.getLevelName(logging.INFO),
            message_model=messages.INVOICE_DATA_NOT_FOUND_MESSAGE,
            extra={
                "request_params": {
                    "invoice_id": 1,
                    "company_ids": [1],
                }
            },
        ),
        ErrorModel(
            header=Header(
                code=messages.INVOICE_DATA_NOT_FOUND_MESSAGE.code,
                message=messages.INVOICE_DATA_NOT_FOUND_MESSAGE.message,
            ),
            payload=None,
        ).model_dump(mode="json"),
        status.HTTP_422_UNPROCESSABLE_ENTITY,
    ),
    (
        # case 3 : I0004: 指定したcompany_infos_idが所属企業、結合企業に該当しない
        1,
        PeppolHttpException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            log_level=logging.getLevelName(logging.INFO),
            message_model=messages.REQUEST_COMPANY_INFOS_ID_VALIDATION_ERROR,
            extra={"request_params": {"company_infos_id": 1}},
        ),
        None,
        None,
        ErrorModel(
            header=Header(
                code=messages.REQUEST_COMPANY_INFOS_ID_VALIDATION_ERROR.code,
                message=messages.REQUEST_COMPANY_INFOS_ID_VALIDATION_ERROR.message,
            ),
            payload=None,
        ).model_dump(mode="json"),
        status.HTTP_422_UNPROCESSABLE_ENTITY,
    ),
    (
        # case 4 : I9999: サーバーエラー
        1,
        PeppolHttpException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            message_model=messages.INTERNAL_SERVER_ERROR,
        ),
        None,
        None,
        ErrorModel(
            header=Header(
                code=messages.INTERNAL_SERVER_ERROR.code,
                message=messages.INTERNAL_SERVER_ERROR.message,
            ),
            payload=None,
        ).model_dump(mode="json"),
        status.HTTP_500_INTERNAL_SERVER_ERROR,
    ),
]
